routes:
  /: campaign
collections:
  /blog/:
    permalink: /blog/{slug}/
    template: writing-topics
    filter: tag:writing-topics
  /vocabs/:
    permalink: /vocabs/{slug}/
    template: vocabs
    filter: tag:vocabs

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
